language: java
sudo: true
before_install:
  - chmod +x mvnw
cache:
  directories:
    - $HOME/.m2
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: 3cb5a73f-32e0-476e-82a0-2c63d3d3e8b4
  app: davidmares
  on:
    all_branches: true