language: java
sudo: true
before_install:
  - chmod +x mvnw
cache:
  directories:
    - $HOME/.m2
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: 1a6c66db-1e19-4dc8-aa6c-4c05cfa0a721
  app: clv-app
  on:
    all_branches: true