language: java
sudo: true
before_install:
  - chmod +x mvnw
cache:
  directories:
    - $HOME/.m2
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: "e5435b03-35c5-40d7-b2ce-721745123cb7"
  app: clv-akademie-2019
  on:
    all_branches: true