language: java
sudo: true
before_install:
  - chmod +x mvnw
cache:
  directories:
    - $HOME/.m2
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: 5d8bf237-0a52-4e76-8f29-95513b54f688
  app: tarnodmy-airlines
  on:
    all_branches: true