
language: java
sudo: true
before_install:
  - chmod +x mvnw
cache:
  directories:
    - $HOME/.m2
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: 35d68bf4-fb6b-48f3-ba03-7a957df700b4
  app: clv-akademie-udovychenko
  on:
    all_branches: true