swagger: "2.0"
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
host: api.example.com
schemes:
  - https
paths:
  /planes:
    get:
      tags:
        - Airplanes
      operationId: getPlanes
      summary: Returns a list of users.
      description: Optional extended description in Markdown.
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/AirplaneList'
definitions:
  AirplaneList:
    type: array
    items:
      $ref: '#/definitions/Airplane'
  Airplane:
    type: object
    properties:
      registrationSign:
        type: string
      seatsEconomy:
        type: integer
      seatsPremium:
        type: integer
