swagger: "2.0"
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
host: api.example.com
schemes:
  - https
paths:
  /planes:
    get:
      summary: Returns a list of planes.
      description: Optional extended description in Markdown.
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:

definitions:
  PlaneList:
    type: array
    items:
      $ref: '#/definitions/Plane'
  Plane:
    type: object
    properties:
      registrationCode:
        type: string
      firstClass:
        type: integer
      economy:
        type: integer

